# Support Vector Regression (SVR)

## Importing the libraries

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [37]:
dataset = pd.read_csv('Student_performance_data _.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -2].values

In [38]:
print(X)

[[17.  1.  2. ...  0.  1.  0.]
 [18.  0.  1. ...  0.  0.  0.]
 [15.  0.  3. ...  0.  0.  0.]
 ...
 [16.  1.  2. ...  0.  0.  1.]
 [16.  1.  0. ...  1.  1.  0.]
 [16.  1.  2. ...  0.  0.  1.]]


In [39]:
print(y)

[2.92919559 3.04291483 0.11260225 ... 1.14233288 1.80329676 2.14001388]


## Splitting the dataset into the Training set and Test set

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [41]:
print(X_train)

[[16.  0.  1. ...  0.  0.  1.]
 [18.  1.  3. ...  0.  1.  0.]
 [15.  0.  2. ...  1.  1.  1.]
 ...
 [16.  0.  0. ...  1.  0.  0.]
 [18.  1.  1. ...  1.  0.  0.]
 [17.  0.  1. ...  0.  0.  0.]]


In [42]:
print(y_train)

[1.81540172 0.49063006 2.51722898 ... 2.44385726 1.36936997 1.79466711]


In [43]:
print(X_test)

[[18.  0.  0. ...  0.  0.  0.]
 [16.  0.  1. ...  1.  0.  1.]
 [18.  1.  1. ...  1.  0.  0.]
 ...
 [16.  0.  3. ...  0.  0.  0.]
 [17.  0.  2. ...  0.  1.  0.]
 [15.  0.  1. ...  0.  1.  0.]]


In [44]:
print(y_test)

[2.22419746 2.7458588  0.91241562 1.48259597 2.91388765 3.31820803
 0.94713346 2.76182375 2.60026419 1.51366041 4.         0.96694881
 0.64545438 2.34844345 0.28657129 0.55113965 3.05538629 1.86827692
 1.27201011 2.11048797 3.22515828 2.40728404 1.92216591 1.2476928
 0.12593308 2.33110892 2.25945115 2.33804636 1.02264173 3.30055221
 2.5538645  1.86875859 2.00462732 3.15402325 1.08449013 0.91233051
 0.31066953 2.32783276 2.12740887 1.36143471 2.93745418 2.02323408
 2.09569136 1.1187524  1.85267174 0.2143195  3.57347421 3.20118196
 2.29308719 1.80441746 3.13376804 4.         0.11524321 2.91813913
 3.38499209 2.26885073 1.69772878 1.58193148 2.12304313 1.72075965
 1.00411266 2.56534732 2.64405986 0.78348664 2.31055729 2.43493438
 0.61893661 1.66431069 2.57344047 2.53977102 2.622179   0.92375323
 0.81301742 2.48921824 1.8080972  0.76831639 2.28387096 1.28322751
 0.52960326 0.36992063 2.32971925 1.35505346 3.51541583 0.85709279
 2.34602574 0.85268236 0.         1.00722582 1.12806836 1.21733

## Training the SVR model on the whole dataset

In [45]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

## Predicting the Test set results

In [46]:
y_pred = regressor.predict(X_test)
for i in range(0,len(y_test)):
    y_test[i]=round(y_test[i],2)
for i in range(0,len(y_pred)):
    y_pred[i]=round(y_pred[i],2)
A=np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
for i in range(0,len(A)):
    print(A[i])

[2.47 2.22]
[2.49 2.75]
[0.7  0.91]
[1.24 1.48]
[3.16 2.91]
[3.2  3.32]
[1.11 0.95]
[2.76 2.76]
[2.27 2.6 ]
[1.28 1.51]
[3.62 4.  ]
[0.97 0.97]
[0.73 0.65]
[2.58 2.35]
[0.65 0.29]
[0.69 0.55]
[3.19 3.06]
[1.9  1.87]
[1.47 1.27]
[2.06 2.11]
[3.47 3.23]
[2.43 2.41]
[1.98 1.92]
[1.56 1.25]
[0.25 0.13]
[2.58 2.33]
[2.22 2.26]
[2.49 2.34]
[1.04 1.02]
[3.06 3.3 ]
[2.78 2.55]
[1.66 1.87]
[2.2 2. ]
[2.77 3.15]
[0.85 1.08]
[0.73 0.91]
[0.29 0.31]
[2.45 2.33]
[2.54 2.13]
[1.41 1.36]
[2.83 2.94]
[2.02 2.02]
[1.68 2.1 ]
[1.19 1.12]
[1.56 1.85]
[0.37 0.21]
[3.6  3.57]
[2.95 3.2 ]
[2.19 2.29]
[1.91 1.8 ]
[2.91 3.13]
[3.52 4.  ]
[0.05 0.12]
[2.86 2.92]
[3.35 3.38]
[2.3  2.27]
[1.39 1.7 ]
[1.92 1.58]
[2.21 2.12]
[1.48 1.72]
[1.36 1.  ]
[2.18 2.57]
[2.72 2.64]
[0.77 0.78]
[2.27 2.31]
[2.11 2.43]
[0.87 0.62]
[1.81 1.66]
[2.36 2.57]
[2.76 2.54]
[2.6  2.62]
[0.84 0.92]
[0.77 0.81]
[2.48 2.49]
[1.49 1.81]
[0.38 0.77]
[2.5  2.28]
[1.21 1.28]
[0.85 0.53]
[0.57 0.37]
[2.51 2.33]
[1.28 1.36]
[3.25 3.52]
[1.04 

## Error in Prediction

In [47]:
total_error=0
for i in range(0,len(A)):
    error=abs(A[i][0]-A[i][1])
    total_error+=error
Final_error=total_error/len(A)
print(Final_error)

0.1657023411371238
